#!/system/bin/sh

rm -rf /data/adb/service.d/ol2.sh
rm -rf /data/adb/modules/HideNavBar/
cmd overlay disable com.android.shell:test
cmd overlay disable com.android.shell:test2
cmd overlay disable com.android.shell:test3
cmd overlay disable com.android.shell:test4
cmd overlay disable com.android.shell:test5
echo "Module Removed"
